ground:
  sequences: 3
  names: ground-0
  topics:
    ground_truth:
      src: /gnss/ground_truth
      type: nav_msgs/msg/Odometry
    gps/fix:
      src: /gnss/gps
      type: sensor_msgs/msg/NavSatFix
    imu:
      src: /gnss/imu
      type: sensor_msgs/msg/Imu
    pointcloud:
      src: /velodyne/points
      type: sensor_msgs/msg/PointCloud2
    camera_left/info:
      src: /camera_left/camera_info
      type: sensor_msgs/msg/CameraInfo
    camera_left/raw:
      src: /camera_right/camera_info
      type: sensor_msgs/msg/CameraInfo
    camera_right/info:
      src: /camera_left/image_raw
      type: sensor_msgs/msg/Image
    camera_right/raw:
      src: /camera_right/image_raw
      type: sensor_msgs/msg/Image