Playground-1:
  sequences: 1
  robots: 3
  topics:
    gps/fix:
      src: '/{robot}/fix'
      type: sensor_msgs/msg/NavSatFix
    imu:
      src: '/{robot}/imu/data'
      type: sensor_msgs/msg/Imu
    camera_left/raw:
      src: '/{robot}/left_camera/compressed'
      type: sensor_msgs/msg/CompressedImage
    camera_right/raw:
      src: '/{robot}/right_camera/compressed'
      type: sensor_msgs/msg/CompressedImage
    pointcloud:
      src: '/{robot}/velodyne_points'
      type: sensor_msgs/msg/PointCloud2
